[features]
seeds = false
skip-lint = false
[programs.devnet]
quilt = "6KxyJHxLPmrwnCb2fqVb37ufwAUZWL6g4CNQPJ78eX7i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ajay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
